### ISSUE TITLE
Calibre web 豆瓣搜索不能正常工作

### ISSUE THREAD

**Issue by liliaow567** [gshang2017/docker#124]
在openwrt系统上使用
docker 使用了 0.6.18 - fee76741a02899d2dfdc2ce29cfc27901a06383c 版本
已经设置了ENABLE_DOUBAN_SEARCH=true
点击豆瓣搜索，显示搜索错误，查看了日志，显示如下
```
[2022-06-10 11:11:53,849]  WARN {cps.metadata_provider.douban:86} HTTPSConnectionPool(host='www.douban.com', port=443): Max retries exceeded with url: /j/search?cat=1001&q=%E5%9F%BA%E7%A1%80%E6%9C%89%E6%9C%BA%E5%8C%96%E5%AD%A6 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa677ef70>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2022-06-10 11:11:53,850] ERROR {cps:1457} Exception on /metadata/search [POST]
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/lib/python3.9/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/usr/local/calibre-web/app/cps/search_metadata.py", line 141, in metadata_search
    data.extend([asdict(x) for x in future.result()])
TypeError: 'NoneType' object is not iterable
```
请求援助

**Comment by gshang2017** [comment]
豆瓣搜索一段时间内次数用多了会被豆瓣限制。

**Comment by liliaow567** [comment]
你好，问题已经解决了。
我今天发现，这可能是因为我的docker容器没有网络导致的。我进入我的容器中，发现无法ping通百度，然后更改了关于docker网络的防火墙规则，之后豆瓣搜索就可以使用了。
感谢您的回复，祝您身体健康！

**Comment by liliaow567** [comment]
> 你好，问题已经解决了。 我今天发现，这可能是因为我的docker容器没有网络导致的。我进入我的容器中，发现无法ping通百度，然后更改了关于docker网络的防火墙规则，之后豆瓣搜索就可以使用了。 感谢您的回复，祝您身体健康！

@gshang2017

**Comment by bcqingfeng** [comment]
> 

请问这个防火墙应该如何设置？
