### ISSUE TITLE
上传图书时报错无法导入lxml.etree.ParserError: Document is empty

### ISSUE THREAD

**Issue by album-GitHub** [gshang2017/docker#132]
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/calibre-web/app/cps/usermanagement.py", line 35, in decorated_view
    return login_required(func)(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/usr/local/calibre-web/app/cps/editbooks.py", line 59, in inner
    return f(*args, **kwargs)
  File "/usr/local/calibre-web/app/cps/editbooks.py", line 1087, in upload
    modify_date |= edit_book_comments(Markup(meta.description).unescape(), db_book)
  File "/usr/local/calibre-web/app/cps/editbooks.py", line 469, in edit_book_comments
    comments = clean_html(comments)
  File "src/lxml/html/clean.py", line 562, in lxml.html.clean.Cleaner.clean_html
  File "/usr/lib/python3.9/site-packages/lxml/html/__init__.py", line 875, in fromstring
    doc = document_fromstring(html, parser=parser, base_url=base_url, **kw)
  File "/usr/lib/python3.9/site-packages/lxml/html/__init__.py", line 763, in document_fromstring
    raise etree.ParserError(
lxml.etree.ParserError: Document is empty

上传的图书：链接:https://pan.baidu.com/s/1kzpbWUCtbvscfOlTl3Kn1w?pwd=nyyz 提取码:nyyz

**Comment by album-GitHub** [comment]
用window版的calibre可以识别，，重新转换成epub格式后再导入就正常

**Comment by gshang2017** [comment]
你可以试下自动添加书籍：

 -v /自动添加文件夹:/autoaddbooks
