### ISSUE TITLE
PDT转换失败

### ISSUE THREAD

**Issue by rainsuns** [gshang2017/docker#15]
[2020-02-29 18:27:58,004]  INFO {cps.editbooks:741} converting: book id: 7 from: PDF to: EPUB
[2020-02-29 18:27:58,156] DEBUG {cps.kobo:420} Unknown Request received: http://192.168.4.5:8083/static/js/libs/bootstrap-datepicker/locales/bootstrap-datepicker.zh_Hans_CN.min.js
[2020-02-29 18:27:58,188]  INFO {cps.worker:291} Book id 7 - target format of .epub does not exist. Moving forward with convert.
[2020-02-29 18:27:59,315] DEBUG {cps.worker:355} 1% 将输入转换为HTML中...
[2020-02-29 18:27:59,316] DEBUG {cps.worker:355} InputFormatPlugin: PDF Input running
[2020-02-29 18:27:59,316] DEBUG {cps.worker:355} on /library/Shi Yue Wen/100Ge Shi Jie Jing Dian Bei Hou De Gu Shi (7)/100Ge Shi Jie Jing Dian Bei Hou De Gu Shi - Shi Yue Wen.pdf
[2020-02-29 18:27:59,388] DEBUG {cps.worker:355} 
[2020-02-29 18:27:59,389] DEBUG {cps.worker:367} Traceback (most recent call last):
[2020-02-29 18:27:59,389] DEBUG {cps.worker:367}   File "site.py", line 77, in main
[2020-02-29 18:27:59,390] DEBUG {cps.worker:367}   File "site-packages/calibre/ebooks/conversion/cli.py", line 401, in main
[2020-02-29 18:27:59,390] DEBUG {cps.worker:367}   File "site-packages/calibre/ebooks/conversion/plumber.py", line 1110, in run
[2020-02-29 18:27:59,390] DEBUG {cps.worker:367}   File "site-packages/calibre/customize/conversion.py", line 246, in __call__
[2020-02-29 18:27:59,391] DEBUG {cps.worker:367}   File "site-packages/calibre/ebooks/conversion/plugins/pdf_input.py", line 54, in convert
[2020-02-29 18:27:59,391] DEBUG {cps.worker:367}   File "site-packages/calibre/ebooks/pdf/pdftohtml.py", line 89, in pdftohtml
[2020-02-29 18:27:59,391] DEBUG {cps.worker:367} ConversionError: pdftohtml failed with return code: -11
[2020-02-29 18:27:59,391] DEBUG {cps.worker:367} /opt/calibre/bin/pdftohtml: /usr/lib/libstdc++.so.6: no version information available (required by /opt/calibre/bin/pdftohtml)
[2020-02-29 18:27:59,392] DEBUG {cps.worker:367} /opt/calibre/bin/pdftohtml: /usr/lib/libstdc++.so.6: no version information available (required by /opt/calibre/bin/pdftohtml)
[2020-02-29 18:27:59,392] DEBUG {cps.worker:367} /opt/calibre/bin/pdftohtml: /usr/lib/libstdc++.so.6: no version information available (required by /opt/calibre/lib/libpoppler.so.66)
[2020-02-29 18:27:59,392] DEBUG {cps.worker:367} /opt/calibre/bin/pdftohtml: /usr/lib/libstdc++.so.6: no version information available (required by /opt/calibre/lib/libpoppler.so.66)
[2020-02-29 18:27:59,393] DEBUG {cps.worker:367} /opt/calibre/bin/pdftohtml: Relink `/lib/libuuid.so.1' with `/usr/glibc-compat/lib/libc.so.6' for IFUNC symbol `strncpy'
[2020-02-29 18:27:59,393]  INFO {cps.worker:392} ebook converter failed with error while converting book
[2020-02-29 18:27:59,393] ERROR {cps.worker:531} Calibre failed with error: /opt/calibre/bin/pdftohtml: Relink `/lib/libuuid.so.1' with `/usr/glibc-compat/lib/libc.so.6' for IFUNC symbol `strncpy'

**Comment by rainsuns** [comment]
calibre-web镜像，群晖安装

**Comment by gshang2017** [comment]
已更新，PDF转换建议下载桌面版calibre。
