### ISSUE TITLE
群晖calibre-web镜像，能否实现目录添加书籍

### ISSUE THREAD

**Issue by wudiming** [gshang2017/docker#16]
大神，请教一下。群晖calibre-web镜像，能否实现目录添加书籍。还有就是添加的书籍能自动获取图书信息么，因为量比较大，一个个添加图书信息挺麻烦的，望指教，谢谢

**Comment by gshang2017** [comment]
上传时进入文件夹，选择一本书籍，然后Ctrl+A即可全选书籍。建议用calibre-server(需配置用户名和密码)上传， 图书自带的基本信息是可以读取的。简介这种就只能一个个添加。

**Comment by wudiming** [comment]
我意思是图书目录下有子文件夹的情况，这个问题我用桌面版解决了，桌面版导入后把图书和数据库都复制过去就好了...

**Comment by gshang2017** [comment]
你可以把桌面版calibre的书库切换为calibre-web的书库，再从桌面版添加。

**Comment by wudiming** [comment]
好的谢谢大佬

**Comment by wudiming** [comment]
哥们，目前出现了一个问题，账户信息点击显示这个错误，账户信息没法修改了，有解决方法不，求助谢谢

Internal Server Error
500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
Traceback (most recent call last):
File "/usr/local/calibre-web/cps/helper.py", line 693, in speaking_language
cur_l = LC.parse(lang.lang_code)
File "/usr/lib/python3.8/site-packages/babel/core.py", line 331, in parse
raise UnknownLocaleError(input_id)
babel.core.UnknownLocaleError: unknown locale 'enm'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/lib/python3.8/site-packages/flask/app.py", line 2446, in wsgi_app
response = self.full_dispatch_request()
File "/usr/lib/python3.8/site-packages/flask/app.py", line 1951, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/lib/python3.8/site-packages/flask/app.py", line 1820, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
raise value
File "/usr/lib/python3.8/site-packages/flask/app.py", line 1949, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/lib/python3.8/site-packages/flask/app.py", line 1935, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/usr/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
return func(*args, **kwargs)
File "/usr/local/calibre-web/cps/web.py", line 1295, in profile
languages = speaking_language()
File "/usr/local/calibre-web/cps/helper.py", line 696, in speaking_language
lang.name = _(isoLanguages.get(part3=lang.lang_code).name)
File "/usr/lib/python3.8/site-packages/iso639/iso639.py", line 265, in get
return getattr(self, key)[value]
File "/usr/lib/python3.8/site-packages/iso639/iso639.py", line 105, in __get__
val = self.f(instance)
File "/usr/lib/python3.8/site-packages/iso639/iso639.py", line 186, in part3
return dict((x.part3, x) for x in self.languages if x.part3)
File "/usr/lib/python3.8/site-packages/iso639/iso639.py", line 105, in __get__
val = self.f(instance)
File "/usr/lib/python3.8/site-packages/iso639/iso639.py", line 174, in languages
l, i, m, p5, p2, p1 = _fabtabular()
File "/usr/lib/python3.8/site-packages/iso639/iso639.py", line 20, in _fabtabular
from pkg_resources import resource_filename
ImportError: cannot import name 'resource_filename' from 'pkg_resources' (unknown location)
Please report this issue with all related information: 创建issue
回到首页

**Comment by gshang2017** [comment]
未复现错误，请更新到最新镜像重试，如再出现，请说下具体复现步骤。

**Comment by wudiming** [comment]
似乎是图书加多了，数据库吃不消导致的！？加了5k+的图书之后就打不开用户信息页面了，备份数据库到别的目录后删除，自动重建空白数据库后又可以正常打开了，但是复制回原数据库，错误复现

**Comment by wudiming** [comment]
镜像已经拉取最新版本

**Comment by gshang2017** [comment]
应该不是图书多的问题。或许是某些特定图书造成的。

**Comment by wudiming** [comment]
那这个问题就挺难解决了啊，很难排查是哪个图书产生的问题0 0
