### ISSUE TITLE
epub格式的图书，经过豆瓣元数据更新后，保存元数据异常，且无法进行阅读

### ISSUE THREAD

**Issue by Pan06da** [gshang2017/docker#214]
### 情况描述：
不管是通过autoaddbook还是手动的通过前端页面进行书籍导入，第一次完成书籍添加后是能够进行正常的阅读的，并且豆瓣元获取数据也都是正常的。 如下方所示
<img width="1589" alt="截屏2023-12-20 08 36 46" src="https://github.com/gshang2017/docker/assets/93591234/7515f01e-6cf4-4af8-b52b-2e49a01d9dd4">
<img width="1366" alt="截屏2023-12-20 08 37 21" src="https://github.com/gshang2017/docker/assets/93591234/0f4cb3ad-23a9-4b8c-91dc-f0254d92d1a7">
<img width="1156" alt="截屏2023-12-20 08 38 22" src="https://github.com/gshang2017/docker/assets/93591234/c2ec811a-9f13-480a-9596-9ed7cf68fe60">

但是当在完成一次豆瓣元的数据匹配后，会发现

1. 首次点击保存匹配结果时cover获取失效
2. 书籍无法在点开预览，页面长时间加载
3. 后台查看library目录发现【目录变更】，匹配元数据后，会把图书文件移动到新的作者和书籍名录下。请参考最后一张附图（这个可能就是问题）

<img width="1215" alt="截屏2023-12-20 08 38 05" src="https://github.com/gshang2017/docker/assets/93591234/e67629b2-7
<img width="1027" alt="截屏2023-12-20 08 38 49" src="https://github.com/gshang2017/docker/assets/93591234/214ec7f6-27b9-4e3b-ae04-ebda4fcf09a8">
266-491b-a2f3-ea94e6364c45">
<img width="485" alt="截屏2023-12-20 08 47 50" src="https://github.com/gshang2017/docker/assets/93591234/d22a7011-dcda-4cd6-85e4-0d34d492ee6c">

### 系统情况：
群晖的DSM7.2系统，用container内部署0.6.21，其他的功能目前均属正常。

<img width="669" alt="截屏2023-12-20 08 52 48" src="https://github.com/gshang2017/docker/assets/93591234/f51587ad-55f7-447d-9bbc-6fdccf22c10f">
<img width="721" alt="截屏2023-12-20 08 53 24" src="https://github.com/gshang2017/docker/assets/93591234/575e8fa3-4e8c-4c95-b21b-e8e287539f46">

**Comment by Pan06da** [comment]
通过autoaddbook目录进行添加的时候，系统会出现这样的错误提示：
`500 Internal Server Error
The server encountered an internal error and was unable to complete your request. There is an error in the application.
Traceback (most recent call last):
File "/usr/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
self.dialect.do_execute(
File "/usr/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
cursor.execute(statement, parameters)
sqlite3.OperationalError: database is locked
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/usr/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
response = self.full_dispatch_request()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
rv = self.handle_user_exception(e)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
rv = self.dispatch_request()
^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/calibre-web/app/cps/usermanagement.py", line 35, in decorated_view
return login_required(func)(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/site-packages/flask_login/utils.py", line 290, in decorated_view
return current_app.ensure_sync(func)(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/calibre-web/app/cps/web.py", line 790, in index
return render_books_list("newest", sort_param, 1, page)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/calibre-web/app/cps/web.py", line 408, in render_books_list
entries, random, pagination = calibre_db.fill_indexpage(page, 0, db.Books, True, order[0],
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/calibre-web/app/cps/db.py", line 803, in fill_indexpage
return self.fill_indexpage_with_archived_books(page, database, pagesize, db_filter, order, False,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/calibre-web/app/cps/db.py", line 813, in fill_indexpage_with_archived_books
.limit(self.config.config_random_books).all())
^^^^^
File "/usr/lib/python3.11/site-packages/sqlalchemy/orm/query.py", line 2773, in all
return self._iter().all()
^^^^^^^^^^^^
File "/usr/lib/python3.11/site-packages/sqlalchemy/orm/query.py", line 2916, in _iter
result = self.session.execute(
^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1717, in execute
result = conn._execute_20(statement, params or {}, execution_options)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1710, in _execute_20
return meth(self, args_10style, kwargs_10style, execution_options)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
return connection._execute_clauseelement(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1577, in _execute_clauseelement
ret = self._execute_context(
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1953, in _execute_context
self._handle_dbapi_exception(
File "/usr/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2134, in _handle_dbapi_exception
util.raise_(
File "/usr/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
raise exception
File "/usr/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
self.dialect.do_execute(
File "/usr/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
[SQL: SELECT books.id AS books_id, books.title AS books_title, books.sort AS books_sort, books.author_sort AS books_author_sort, books.timestamp AS books_timestamp, books.pubdate AS books_pubdate, books.series_index AS books_series_index, books.last_modified AS books_last_modified, books.path AS books_path, books.has_cover AS books_has_cover, books.uuid AS books_uuid, books.isbn AS books_isbn, books.flags AS books_flags, archived_book.is_archived AS archived_book_is_archived, book_read_link.read_status AS book_read_link_read_status
FROM books LEFT OUTER JOIN book_read_link ON book_read_link.user_id = ? AND book_read_link.book_id = books.id LEFT OUTER JOIN archived_book ON books.id = archived_book.book_id AND archived_book.user_id = ?
WHERE (books.id NOT IN (?, ?)) ORDER BY random()
LIMIT ? OFFSET ?]
[parameters: (1, 1, 99, 213, 4, 0)]
(Background on this error at: https://sqlalche.me/e/14/e3q8)`
