### ISSUE TITLE
calibre-web的docker更新后就一直报错了，日志显示需要pip install regex，SSH进去输入也报错

### ISSUE THREAD

**Issue by BenBenJian** [gshang2017/docker#229]
calibre-web的docker更新后就一直报错了，日志显示需要pip install regex，SSH进去输入也报错
这个怎么搞

**Comment by BenBenJian** [comment]
补充一下，是部署后，在calibre-web中用内置的更新又更新了一次才这样。

**Comment by gshang2017** [comment]
更新后需要进容器更新依赖，你可以试试。

pip3 install --no-cache-dir --break-system-package -r /usr/local/calibre-web/app/requirements.txt

pip3 install --no-cache-dir --break-system-package -r /usr/local/calibre-web/app/optional-requirements.txt

**Comment by BenBenJian** [comment]
非常感谢，我试试

**Comment by sliasyang** [comment]
我之前版本0.6.24-7.9.0 没有这个问题，更新最新版本后，启动阶段有如下报错

date	stream	content
2025/04/21 17:03:48	stdout	ModuleNotFoundError: No module named 'flask'
2025/04/21 17:03:48	stdout	    from flask import Flask
2025/04/21 17:03:48	stdout	  File "/usr/local/calibre-web/app/cps/__init__.py", line 28, in <module>
2025/04/21 17:03:48	stdout	    from cps.main import main
2025/04/21 17:03:48	stdout	  File "/usr/local/calibre-web/app/cps.py", line 28, in <module>
2025/04/21 17:03:48	stdout	Traceback (most recent call last):

这个是不是启动后也需要手工去容器里面更新起依赖？

**Comment by gshang2017** [comment]
只有用calibre-web内置的更新更新后可能需要手动安装依赖。如果直接拉取的最新版，应该不会出现依赖问题。

**Comment by sliasyang** [comment]
> 只有用calibre-web内置的更新更新后可能需要手动安装依赖。如果直接拉取的最新版，应该不会出现依赖问题。

我是直接拉取的最新镜像，然后重置容器安装的。 启动就一直反复报这个错。 白群晖220+ 
回退镜像为 0.6.24-7.9.0 就一切正常

**Comment by gshang2017** [comment]
删掉镜像重新拉取试下。或者拉取带标签的   docker pull johngong/calibre-web:0.6.24-8.0.1

**Comment by sliasyang** [comment]
> 删掉镜像重新拉取试下。或者拉取带标签的 docker pull johngong/calibre-web:0.6.24-8.0.1

试过了。。。我删除镜像，删除容器，重新配置，也是一样，只要是拉取最新latest镜像就是这个结果

**Comment by sliasyang** [comment]
我在path中添加了/opt/venv/bin，问题现象相同。 当前暂时回退到0.6.24-7.9.0使用正常。
附件为我的docker配置导出文件，供参考

[johngong-calibre-web1-1.syno.json](https://github.com/user-attachments/files/19833994/johngong-calibre-web1-1.syno.json)

**Comment by gshang2017** [comment]
/opt/venv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

**Comment by sliasyang** [comment]
> /opt/venv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

果然就是这个问题！ 多谢大佬~~~修改后可以了
