### ISSUE TITLE
5.0.0-5.0.0.10版本peers界面空白

### ISSUE THREAD

**Issue by starlightor** [gshang2017/docker#243]
错误代码：

```
Uncaught ReferenceError: getSyncMainDataInterval is not defined
    at Object.onComplete (prop-peers.js:71:62)
    at Object.<anonymous> (MooTools-Core-1.6.0-compat-compressed.js:5:19487)
    at Array.forEach (<anonymous>)
    at Function.forEach (MooTools-Core-1.6.0-compat-compressed.js:5:2711)
    at Array.each (MooTools-Core-1.6.0-compat-compressed.js:5:4561)
    at Object.fireEvent (MooTools-Core-1.6.0-compat-compressed.js:5:19448)
    at r.extend.$owner (MooTools-Core-1.6.0-compat-compressed.js:5:18121)
    at Object.onSuccess (MooTools-Core-1.6.0-compat-compressed.js:7:23951)
    at r.extend.$owner (MooTools-Core-1.6.0-compat-compressed.js:5:18121)
    at Object.success (MooTools-Core-1.6.0-compat-compressed.js:7:30349)
```

**Comment by rolay** [comment]
+1，看官方的代码已经修复
