### ISSUE TITLE
您好，我使用johngong/calibre-web，无法上传书籍

### ISSUE THREAD

**Issue by iseamount** [gshang2017/docker#66]
大神您好。我使用johngong/calibre-web，无法添加书籍。

calibre, version 5.10.0
错误： 加入文件时出错: 无法添加任何书籍，点击“查看详情”以获取更多信息

----------------------------------------------------------------------
无法添加书籍：挚友
	/Volumes/NO NAME/《挚友》川端康成.azw3
错误：
Traceback (most recent call last):
  File "calibre/gui2/add.py", line 457, in add_book
  File "calibre/db/legacy.py", line 334, in create_book_entry
  File "calibre/db/cache.py", line 72, in call_func_with_lock
  File "calibre/db/cache.py", line 1683, in create_book_entry
  File "calibre/db/cache.py", line 1392, in set_metadata
  File "calibre/db/cache.py", line 1378, in set_field
  File "calibre/db/cache.py", line 1198, in set_field
  File "calibre/db/write.py", line 543, in set_books
  File "calibre/db/write.py", line 466, in many_many
  File "calibre/db/backend.py", line 932, in executemany
apsw.ConstraintError: ConstraintError: Foreign key violation: authors is still referenced

添加书籍使用了mac 或window 版本的calibre，版本也用了最新版或是5.10版本。添加任何书籍都是这样，还请大神指导。

（前几天还都是好好地，奇怪了）

**Comment by gshang2017** [comment]
可能你书库的数据库有损坏。可以用桌面版calibre-电子书-书库维护-恢复数据库试下。
